<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);CC0022;CC0057;CC0091;MA0004</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoFixture" Version="4.18.1" />
    <PackageReference Include="AutoFixture.AutoMoq" Version="4.18.1" />
    <PackageReference Include="AutoFixture.SeedExtensions" Version="4.18.1" />
    <PackageReference Include="AutoFixture.Xunit2" Version="4.18.1" />
    <PackageReference Include="AwesomeAssertions " Version="9.4.0" />
    <PackageReference Include="AwesomeAssertions.Analyzers" Version="9.0.8" />
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="coverlet.collector" Version="8.0.1" />
    <PackageReference Include="coverlet.msbuild" Version="8.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Moq.Analyzers" Version="0.4.2" />
    <PackageReference Include="NunitXml.TestLogger" Version="8.0.0" />
    <PackageReference Include="SemanticComparison" Version="4.1.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.categories" Version="3.0.1" />
    <PackageReference Include="xunit.analyzers" Version="1.27.0" />
    <PackageReference Include="xunit.runner.console" Version="2.9.3" />
    <PackageReference Include="XunitXml.TestLogger" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net462' OR '$(TargetFramework)' == 'net47' OR '$(TargetFramework)' == 'net471'">
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.3" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' != 'net462' AND '$(TargetFramework)' != 'net47' AND '$(TargetFramework)' != 'net471'">
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>
