<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Remove="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
    <PackageReference Include="MySql.Data" Version="26.7.0" />
    <ProjectReference Include="..\..\..\src\AdaskoTheBeAsT.Identity.Dapper.MySql\AdaskoTheBeAsT.Identity.Dapper.MySql.csproj" />
    <ProjectReference Include="..\..\..\src\AdaskoTheBeAsT.Identity.Dapper\AdaskoTheBeAsT.Identity.Dapper.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="Microsoft.Data.SqlClient" Version="7.1.1" />
    <PackageReference Update="Npgsql" Version="10.0.3" />
    <PackageReference Update="Oracle.ManagedDataAccess.Core" Version="23.26.301" />
  </ItemGroup>
</Project>
