CREATE TABLE [dbo].[AspNetClaims]
(
	[Id]          INT IDENTITY (1, 1) NOT NULL,
    [ClaimTypeId] INT NOT NULL,
    [Value]       NVARCHAR (256) NOT NULL,
	[SysStart]    DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
	[SysEnd]      DATETIME2 (7) GENERATED ALWAYS AS ROW END NOT NULL,
	PERIOD FOR SYSTEM_TIME ([SysStart], [SysEnd]),
    CONSTRAINT [PK_AspNetClaims] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_AspNetClaims_AspNetClaimTypes_ClaimTypeId] FOREIGN KEY ([ClaimTypeId]) REFERENCES [dbo].[AspNetClaimTypes] ([Id]) ON DELETE CASCADE
)
WITH (SYSTEM_VERSIONING = ON(HISTORY_TABLE=[dbo].[AspNetClaims_HISTORY], DATA_CONSISTENCY_CHECK=ON))
