// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace AdaskoTheBeAsT.Identity.Dapper.MySql.IntegrationTest.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class WithoutNormalizedAspNetIdentityGuidUserOnlyStoreFeature : object, global::Xunit.IClassFixture<WithoutNormalizedAspNetIdentityGuidUserOnlyStoreFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "WithoutNormalizedAspNetIdentityGuidUserOnlyStore.feature"
#line hidden
        
        public WithoutNormalizedAspNetIdentityGuidUserOnlyStoreFeature(WithoutNormalizedAspNetIdentityGuidUserOnlyStoreFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/WithoutNormalizedAspNetIdentityGuidUserOnlyStore.feature.ndjson", 58);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Verify lightweight UserOnlyStore method <method> without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Verify lightweight UserOnlyStore method <method> without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        [global::Xunit.InlineDataAttribute("Dispose", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("GetUserIdAsync", "1", new string[0])]
        [global::Xunit.InlineDataAttribute("GetUserNameAsync", "2", new string[0])]
        [global::Xunit.InlineDataAttribute("SetUserNameAsync", "3", new string[0])]
        [global::Xunit.InlineDataAttribute("GetNormalizedUserNameAsync", "4", new string[0])]
        [global::Xunit.InlineDataAttribute("SetNormalizedUserNameAsync", "5", new string[0])]
        [global::Xunit.InlineDataAttribute("ConvertIdFromString", "6", new string[0])]
        [global::Xunit.InlineDataAttribute("ConvertIdToString", "7", new string[0])]
        [global::Xunit.InlineDataAttribute("SetPasswordHashAsync", "8", new string[0])]
        [global::Xunit.InlineDataAttribute("GetPasswordHashAsync", "9", new string[0])]
        [global::Xunit.InlineDataAttribute("HasPasswordAsync", "10", new string[0])]
        [global::Xunit.InlineDataAttribute("GetEmailConfirmedAsync", "11", new string[0])]
        [global::Xunit.InlineDataAttribute("SetEmailConfirmedAsync", "12", new string[0])]
        [global::Xunit.InlineDataAttribute("SetEmailAsync", "13", new string[0])]
        [global::Xunit.InlineDataAttribute("GetEmailAsync", "14", new string[0])]
        [global::Xunit.InlineDataAttribute("GetNormalizedEmailAsync", "15", new string[0])]
        [global::Xunit.InlineDataAttribute("SetNormalizedEmailAsync", "16", new string[0])]
        [global::Xunit.InlineDataAttribute("GetLockoutEndDateAsync", "17", new string[0])]
        [global::Xunit.InlineDataAttribute("SetLockoutEndDateAsync", "18", new string[0])]
        [global::Xunit.InlineDataAttribute("ResetAccessFailedCountAsync", "19", new string[0])]
        [global::Xunit.InlineDataAttribute("GetAccessFailedCountAsync", "20", new string[0])]
        [global::Xunit.InlineDataAttribute("GetLockoutEnabledAsync", "21", new string[0])]
        [global::Xunit.InlineDataAttribute("SetLockoutEnabledAsync", "22", new string[0])]
        [global::Xunit.InlineDataAttribute("SetPhoneNumberAsync", "23", new string[0])]
        [global::Xunit.InlineDataAttribute("GetPhoneNumberAsync", "24", new string[0])]
        [global::Xunit.InlineDataAttribute("GetPhoneNumberConfirmedAsync", "25", new string[0])]
        [global::Xunit.InlineDataAttribute("SetPhoneNumberConfirmedAsync", "26", new string[0])]
        [global::Xunit.InlineDataAttribute("SetSecurityStampAsync", "27", new string[0])]
        [global::Xunit.InlineDataAttribute("GetSecurityStampAsync", "28", new string[0])]
        [global::Xunit.InlineDataAttribute("SetTwoFactorEnabledAsync", "29", new string[0])]
        [global::Xunit.InlineDataAttribute("GetTwoFactorEnabledAsync", "30", new string[0])]
        public async global::System.Threading.Tasks.Task VerifyLightweightUserOnlyStoreMethodMethodWithoutNormalizedAndGuidId(string method, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("method", method);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify lightweight UserOnlyStore method <method> without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
 await testRunner.WhenAsync(string.Format("I verify \"{0}\" on MySQL UserOnlyStore without normalized and Guid id", method), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
 await testRunner.ThenAsync(string.Format("\"{0}\" on MySQL UserOnlyStore should work without normalized and Guid id", method), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Query Users with Users without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Query Users with Users without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task QueryUsersWithUsersWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "31";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Query Users with Users without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 46
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 47
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table27 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table27.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 48
 await testRunner.AndAsync("I created users for MySQL UserOnlyStore", ((string)(null)), table27, "And ");
#line hidden
                global::Reqnroll.Table table28 = new global::Reqnroll.Table(new string[] {
                            "Name"});
                table28.AddRow(new string[] {
                            "Admin"});
#line 51
 await testRunner.AndAsync("I created roles for MySQL UserOnlyStore", ((string)(null)), table28, "And ");
#line hidden
                global::Reqnroll.Table table29 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "RoleName"});
                table29.AddRow(new string[] {
                            "John",
                            "Admin"});
#line 54
 await testRunner.AndAsync("I added users to roles for MySQL UserOnlyStore", ((string)(null)), table29, "And ");
#line hidden
#line 57
 await testRunner.WhenAsync("I execute \"Users\" on MySQL UserOnlyStore", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table30 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table30.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 58
 await testRunner.ThenAsync("the last users result for MySQL UserOnlyStore should match", ((string)(null)), table30, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Create user with CreateAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Create user with CreateAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task CreateUserWithCreateAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "32";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create user with CreateAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 63
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 64
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table31 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table31.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 65
 await testRunner.WhenAsync("I execute \"CreateAsync\" on MySQL UserOnlyStore with parameters", ((string)(null)), table31, "When ");
#line hidden
#line 68
 await testRunner.ThenAsync("the last identity result for MySQL UserOnlyStore should be successful", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table32 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table32.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 69
 await testRunner.AndAsync("the last user result for MySQL UserOnlyStore should match", ((string)(null)), table32, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Update user with UpdateAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Update user with UpdateAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task UpdateUserWithUpdateAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "33";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Update user with UpdateAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 74
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 75
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table33 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table33.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 76
 await testRunner.AndAsync("I created users for MySQL UserOnlyStore", ((string)(null)), table33, "And ");
#line hidden
                global::Reqnroll.Table table34 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "NewUserName",
                            "NewEmail"});
                table34.AddRow(new string[] {
                            "John",
                            "Johnny",
                            "johnny@example.com"});
#line 79
 await testRunner.WhenAsync("I execute \"UpdateAsync\" on MySQL UserOnlyStore with parameters", ((string)(null)), table34, "When ");
#line hidden
#line 82
 await testRunner.ThenAsync("the last identity result for MySQL UserOnlyStore should be successful", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table35 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table35.AddRow(new string[] {
                            "Johnny",
                            "johnny@example.com"});
#line 83
 await testRunner.AndAsync("the last user result for MySQL UserOnlyStore should match", ((string)(null)), table35, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Delete user with DeleteAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Delete user with DeleteAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task DeleteUserWithDeleteAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "34";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Delete user with DeleteAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 88
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 89
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table36 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table36.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 90
 await testRunner.AndAsync("I created users for MySQL UserOnlyStore", ((string)(null)), table36, "And ");
#line hidden
                global::Reqnroll.Table table37 = new global::Reqnroll.Table(new string[] {
                            "UserName"});
                table37.AddRow(new string[] {
                            "John"});
#line 93
 await testRunner.WhenAsync("I execute \"DeleteAsync\" on MySQL UserOnlyStore with parameters", ((string)(null)), table37, "When ");
#line hidden
#line 96
 await testRunner.ThenAsync("the last identity result for MySQL UserOnlyStore should be successful", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 97
 await testRunner.AndAsync("the last user result for MySQL UserOnlyStore should be null", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Find user with FindByIdAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Find user with FindByIdAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task FindUserWithFindByIdAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "35";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Find user with FindByIdAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 100
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 101
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table38 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table38.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 102
 await testRunner.AndAsync("I created users for MySQL UserOnlyStore", ((string)(null)), table38, "And ");
#line hidden
                global::Reqnroll.Table table39 = new global::Reqnroll.Table(new string[] {
                            "UserName"});
                table39.AddRow(new string[] {
                            "John"});
#line 105
 await testRunner.WhenAsync("I execute \"FindByIdAsync\" on MySQL UserOnlyStore with parameters", ((string)(null)), table39, "When ");
#line hidden
                global::Reqnroll.Table table40 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table40.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 108
 await testRunner.ThenAsync("the last user result for MySQL UserOnlyStore should match", ((string)(null)), table40, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Find user with FindByNameAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Find user with FindByNameAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task FindUserWithFindByNameAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "36";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Find user with FindByNameAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 113
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 114
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table41 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table41.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 115
 await testRunner.AndAsync("I created users for MySQL UserOnlyStore", ((string)(null)), table41, "And ");
#line hidden
                global::Reqnroll.Table table42 = new global::Reqnroll.Table(new string[] {
                            "UserName"});
                table42.AddRow(new string[] {
                            "John"});
#line 118
 await testRunner.WhenAsync("I execute \"FindByNameAsync\" on MySQL UserOnlyStore with parameters", ((string)(null)), table42, "When ");
#line hidden
                global::Reqnroll.Table table43 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table43.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 121
 await testRunner.ThenAsync("the last user result for MySQL UserOnlyStore should match", ((string)(null)), table43, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Find user with FindByEmailAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Find user with FindByEmailAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task FindUserWithFindByEmailAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "37";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Find user with FindByEmailAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 126
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 127
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table44 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table44.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 128
 await testRunner.AndAsync("I created users for MySQL UserOnlyStore", ((string)(null)), table44, "And ");
#line hidden
                global::Reqnroll.Table table45 = new global::Reqnroll.Table(new string[] {
                            "Email"});
                table45.AddRow(new string[] {
                            "john@example.com"});
#line 131
 await testRunner.WhenAsync("I execute \"FindByEmailAsync\" on MySQL UserOnlyStore with parameters", ((string)(null)), table45, "When ");
#line hidden
                global::Reqnroll.Table table46 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table46.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 134
 await testRunner.ThenAsync("the last user result for MySQL UserOnlyStore should match", ((string)(null)), table46, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Get user claims with GetClaimsAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Get user claims with GetClaimsAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task GetUserClaimsWithGetClaimsAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "38";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get user claims with GetClaimsAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 139
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 140
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table47 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table47.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 141
 await testRunner.AndAsync("I created users for MySQL UserOnlyStore", ((string)(null)), table47, "And ");
#line hidden
                global::Reqnroll.Table table48 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "ClaimType",
                            "ClaimValue"});
                table48.AddRow(new string[] {
                            "John",
                            "permission",
                            "read"});
                table48.AddRow(new string[] {
                            "John",
                            "permission",
                            "write"});
#line 144
 await testRunner.AndAsync("I added user claims for MySQL UserOnlyStore", ((string)(null)), table48, "And ");
#line hidden
                global::Reqnroll.Table table49 = new global::Reqnroll.Table(new string[] {
                            "UserName"});
                table49.AddRow(new string[] {
                            "John"});
#line 148
 await testRunner.WhenAsync("I execute \"GetClaimsAsync\" on MySQL UserOnlyStore with parameters", ((string)(null)), table49, "When ");
#line hidden
                global::Reqnroll.Table table50 = new global::Reqnroll.Table(new string[] {
                            "ClaimType",
                            "ClaimValue"});
                table50.AddRow(new string[] {
                            "permission",
                            "read"});
                table50.AddRow(new string[] {
                            "permission",
                            "write"});
#line 151
 await testRunner.ThenAsync("the last claims result for MySQL UserOnlyStore should match", ((string)(null)), table50, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Add user claims with AddClaimsAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Add user claims with AddClaimsAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task AddUserClaimsWithAddClaimsAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "39";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Add user claims with AddClaimsAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 157
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 158
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table51 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table51.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 159
 await testRunner.AndAsync("I created users for MySQL UserOnlyStore", ((string)(null)), table51, "And ");
#line hidden
                global::Reqnroll.Table table52 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "ClaimType",
                            "ClaimValue"});
                table52.AddRow(new string[] {
                            "John",
                            "permission",
                            "read"});
                table52.AddRow(new string[] {
                            "John",
                            "permission",
                            "write"});
#line 162
 await testRunner.WhenAsync("I execute \"AddClaimsAsync\" on MySQL UserOnlyStore with parameters", ((string)(null)), table52, "When ");
#line hidden
                global::Reqnroll.Table table53 = new global::Reqnroll.Table(new string[] {
                            "ClaimType",
                            "ClaimValue"});
                table53.AddRow(new string[] {
                            "permission",
                            "read"});
                table53.AddRow(new string[] {
                            "permission",
                            "write"});
#line 166
 await testRunner.ThenAsync("the last claims result for MySQL UserOnlyStore should match", ((string)(null)), table53, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Replace user claim with ReplaceClaimAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Replace user claim with ReplaceClaimAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task ReplaceUserClaimWithReplaceClaimAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "40";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Replace user claim with ReplaceClaimAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 172
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 173
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table54 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table54.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 174
 await testRunner.AndAsync("I created users for MySQL UserOnlyStore", ((string)(null)), table54, "And ");
#line hidden
                global::Reqnroll.Table table55 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "ClaimType",
                            "ClaimValue"});
                table55.AddRow(new string[] {
                            "John",
                            "permission",
                            "read"});
#line 177
 await testRunner.AndAsync("I added user claims for MySQL UserOnlyStore", ((string)(null)), table55, "And ");
#line hidden
                global::Reqnroll.Table table56 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "ClaimTypeOld",
                            "ClaimValueOld",
                            "ClaimTypeNew",
                            "ClaimValueNew"});
                table56.AddRow(new string[] {
                            "John",
                            "permission",
                            "read",
                            "permission",
                            "write"});
#line 180
 await testRunner.WhenAsync("I execute \"ReplaceClaimAsync\" on MySQL UserOnlyStore with parameters", ((string)(null)), table56, "When ");
#line hidden
                global::Reqnroll.Table table57 = new global::Reqnroll.Table(new string[] {
                            "ClaimType",
                            "ClaimValue"});
                table57.AddRow(new string[] {
                            "permission",
                            "write"});
#line 183
 await testRunner.ThenAsync("the last claims result for MySQL UserOnlyStore should match", ((string)(null)), table57, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Remove user claims with RemoveClaimsAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Remove user claims with RemoveClaimsAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task RemoveUserClaimsWithRemoveClaimsAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "41";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Remove user claims with RemoveClaimsAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 188
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 189
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table58 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table58.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 190
 await testRunner.AndAsync("I created users for MySQL UserOnlyStore", ((string)(null)), table58, "And ");
#line hidden
                global::Reqnroll.Table table59 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "ClaimType",
                            "ClaimValue"});
                table59.AddRow(new string[] {
                            "John",
                            "permission",
                            "read"});
#line 193
 await testRunner.AndAsync("I added user claims for MySQL UserOnlyStore", ((string)(null)), table59, "And ");
#line hidden
                global::Reqnroll.Table table60 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "ClaimType",
                            "ClaimValue"});
                table60.AddRow(new string[] {
                            "John",
                            "permission",
                            "read"});
#line 196
 await testRunner.WhenAsync("I execute \"RemoveClaimsAsync\" on MySQL UserOnlyStore with parameters", ((string)(null)), table60, "When ");
#line hidden
                global::Reqnroll.Table table61 = new global::Reqnroll.Table(new string[] {
                            "ClaimType",
                            "ClaimValue"});
#line 199
 await testRunner.ThenAsync("the last claims result for MySQL UserOnlyStore should match", ((string)(null)), table61, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Add user login with AddLoginAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Add user login with AddLoginAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task AddUserLoginWithAddLoginAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "42";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Add user login with AddLoginAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 203
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 204
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table62 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table62.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 205
 await testRunner.AndAsync("I created users for MySQL UserOnlyStore", ((string)(null)), table62, "And ");
#line hidden
                global::Reqnroll.Table table63 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "LoginProvider",
                            "ProviderKey",
                            "ProviderDisplayName"});
                table63.AddRow(new string[] {
                            "John",
                            "GitHub",
                            "john-gh",
                            "GitHub"});
#line 208
 await testRunner.WhenAsync("I execute \"AddLoginAsync\" on MySQL UserOnlyStore with parameters", ((string)(null)), table63, "When ");
#line hidden
                global::Reqnroll.Table table64 = new global::Reqnroll.Table(new string[] {
                            "LoginProvider",
                            "ProviderKey",
                            "ProviderDisplayName"});
                table64.AddRow(new string[] {
                            "GitHub",
                            "john-gh",
                            "GitHub"});
#line 211
 await testRunner.ThenAsync("the last logins result for MySQL UserOnlyStore should match", ((string)(null)), table64, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Remove user login with RemoveLoginAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Remove user login with RemoveLoginAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task RemoveUserLoginWithRemoveLoginAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "43";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Remove user login with RemoveLoginAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 216
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 217
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table65 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table65.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 218
 await testRunner.AndAsync("I created users for MySQL UserOnlyStore", ((string)(null)), table65, "And ");
#line hidden
                global::Reqnroll.Table table66 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "LoginProvider",
                            "ProviderKey",
                            "ProviderDisplayName"});
                table66.AddRow(new string[] {
                            "John",
                            "GitHub",
                            "john-gh",
                            "GitHub"});
#line 221
 await testRunner.AndAsync("I added user logins for MySQL UserOnlyStore", ((string)(null)), table66, "And ");
#line hidden
                global::Reqnroll.Table table67 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "LoginProvider",
                            "ProviderKey"});
                table67.AddRow(new string[] {
                            "John",
                            "GitHub",
                            "john-gh"});
#line 224
 await testRunner.WhenAsync("I execute \"RemoveLoginAsync\" on MySQL UserOnlyStore with parameters", ((string)(null)), table67, "When ");
#line hidden
                global::Reqnroll.Table table68 = new global::Reqnroll.Table(new string[] {
                            "LoginProvider",
                            "ProviderKey",
                            "ProviderDisplayName"});
#line 227
 await testRunner.ThenAsync("the last logins result for MySQL UserOnlyStore should match", ((string)(null)), table68, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Get user logins with GetLoginsAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Get user logins with GetLoginsAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task GetUserLoginsWithGetLoginsAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "44";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get user logins with GetLoginsAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 231
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 232
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table69 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table69.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 233
 await testRunner.AndAsync("I created users for MySQL UserOnlyStore", ((string)(null)), table69, "And ");
#line hidden
                global::Reqnroll.Table table70 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "LoginProvider",
                            "ProviderKey",
                            "ProviderDisplayName"});
                table70.AddRow(new string[] {
                            "John",
                            "GitHub",
                            "john-gh",
                            "GitHub"});
#line 236
 await testRunner.AndAsync("I added user logins for MySQL UserOnlyStore", ((string)(null)), table70, "And ");
#line hidden
                global::Reqnroll.Table table71 = new global::Reqnroll.Table(new string[] {
                            "UserName"});
                table71.AddRow(new string[] {
                            "John"});
#line 239
 await testRunner.WhenAsync("I execute \"GetLoginsAsync\" on MySQL UserOnlyStore with parameters", ((string)(null)), table71, "When ");
#line hidden
                global::Reqnroll.Table table72 = new global::Reqnroll.Table(new string[] {
                            "LoginProvider",
                            "ProviderKey",
                            "ProviderDisplayName"});
                table72.AddRow(new string[] {
                            "GitHub",
                            "john-gh",
                            "GitHub"});
#line 242
 await testRunner.ThenAsync("the last logins result for MySQL UserOnlyStore should match", ((string)(null)), table72, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Find user by login with FindByLoginAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Find user by login with FindByLoginAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task FindUserByLoginWithFindByLoginAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "45";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Find user by login with FindByLoginAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 247
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 248
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table73 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table73.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 249
 await testRunner.AndAsync("I created users for MySQL UserOnlyStore", ((string)(null)), table73, "And ");
#line hidden
                global::Reqnroll.Table table74 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "LoginProvider",
                            "ProviderKey",
                            "ProviderDisplayName"});
                table74.AddRow(new string[] {
                            "John",
                            "GitHub",
                            "john-gh",
                            "GitHub"});
#line 252
 await testRunner.AndAsync("I added user logins for MySQL UserOnlyStore", ((string)(null)), table74, "And ");
#line hidden
                global::Reqnroll.Table table75 = new global::Reqnroll.Table(new string[] {
                            "LoginProvider",
                            "ProviderKey"});
                table75.AddRow(new string[] {
                            "GitHub",
                            "john-gh"});
#line 255
 await testRunner.WhenAsync("I execute \"FindByLoginAsync\" on MySQL UserOnlyStore with parameters", ((string)(null)), table75, "When ");
#line hidden
                global::Reqnroll.Table table76 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table76.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 258
 await testRunner.ThenAsync("the last user result for MySQL UserOnlyStore should match", ((string)(null)), table76, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Increment access failed count with IncrementAccessFailedCountAsync without normal" +
            "ized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Increment access failed count with IncrementAccessFailedCountAsync without normal" +
            "ized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task IncrementAccessFailedCountWithIncrementAccessFailedCountAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "46";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Increment access failed count with IncrementAccessFailedCountAsync without normal" +
                    "ized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 263
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 264
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table77 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email",
                            "AccessFailedCount"});
                table77.AddRow(new string[] {
                            "John",
                            "john@example.com",
                            "0"});
#line 265
 await testRunner.AndAsync("I created users for MySQL UserOnlyStore", ((string)(null)), table77, "And ");
#line hidden
                global::Reqnroll.Table table78 = new global::Reqnroll.Table(new string[] {
                            "UserName"});
                table78.AddRow(new string[] {
                            "John"});
#line 268
 await testRunner.WhenAsync("I execute \"IncrementAccessFailedCountAsync\" on MySQL UserOnlyStore with parameter" +
                        "s", ((string)(null)), table78, "When ");
#line hidden
#line 271
 await testRunner.ThenAsync("the last integer result for MySQL UserOnlyStore should be 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table79 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "AccessFailedCount"});
                table79.AddRow(new string[] {
                            "John",
                            "1"});
#line 272
 await testRunner.AndAsync("the last user result for MySQL UserOnlyStore should match", ((string)(null)), table79, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Get users for claim with GetUsersForClaimAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Get users for claim with GetUsersForClaimAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task GetUsersForClaimWithGetUsersForClaimAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "47";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get users for claim with GetUsersForClaimAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 277
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 278
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table80 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table80.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 279
 await testRunner.AndAsync("I created users for MySQL UserOnlyStore", ((string)(null)), table80, "And ");
#line hidden
                global::Reqnroll.Table table81 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "ClaimType",
                            "ClaimValue"});
                table81.AddRow(new string[] {
                            "John",
                            "permission",
                            "read"});
#line 282
 await testRunner.AndAsync("I added user claims for MySQL UserOnlyStore", ((string)(null)), table81, "And ");
#line hidden
                global::Reqnroll.Table table82 = new global::Reqnroll.Table(new string[] {
                            "ClaimType",
                            "ClaimValue"});
                table82.AddRow(new string[] {
                            "permission",
                            "read"});
#line 285
 await testRunner.WhenAsync("I execute \"GetUsersForClaimAsync\" on MySQL UserOnlyStore with parameters", ((string)(null)), table82, "When ");
#line hidden
                global::Reqnroll.Table table83 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table83.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 288
 await testRunner.ThenAsync("the last users result for MySQL UserOnlyStore should match", ((string)(null)), table83, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Set token with SetTokenAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Set token with SetTokenAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task SetTokenWithSetTokenAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "48";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Set token with SetTokenAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 293
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 294
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table84 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table84.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 295
 await testRunner.AndAsync("I created users for MySQL UserOnlyStore", ((string)(null)), table84, "And ");
#line hidden
                global::Reqnroll.Table table85 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "LoginProvider",
                            "Name",
                            "Value"});
                table85.AddRow(new string[] {
                            "John",
                            "api",
                            "refresh-token",
                            "refresh-value"});
#line 298
 await testRunner.WhenAsync("I execute \"SetTokenAsync\" on MySQL UserOnlyStore with parameters", ((string)(null)), table85, "When ");
#line hidden
#line 301
 await testRunner.ThenAsync("the last string result for MySQL UserOnlyStore should be \"refresh-value\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Remove token with RemoveTokenAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Remove token with RemoveTokenAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task RemoveTokenWithRemoveTokenAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "49";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Remove token with RemoveTokenAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 304
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 305
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table86 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table86.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 306
 await testRunner.AndAsync("I created users for MySQL UserOnlyStore", ((string)(null)), table86, "And ");
#line hidden
                global::Reqnroll.Table table87 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "LoginProvider",
                            "Name",
                            "Value"});
                table87.AddRow(new string[] {
                            "John",
                            "api",
                            "refresh-token",
                            "refresh-value"});
#line 309
 await testRunner.AndAsync("I added user tokens for MySQL UserOnlyStore", ((string)(null)), table87, "And ");
#line hidden
                global::Reqnroll.Table table88 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "LoginProvider",
                            "Name"});
                table88.AddRow(new string[] {
                            "John",
                            "api",
                            "refresh-token"});
#line 312
 await testRunner.WhenAsync("I execute \"RemoveTokenAsync\" on MySQL UserOnlyStore with parameters", ((string)(null)), table88, "When ");
#line hidden
#line 315
 await testRunner.ThenAsync("the last string result for MySQL UserOnlyStore should be null", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Get token with GetTokenAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Get token with GetTokenAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task GetTokenWithGetTokenAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "50";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get token with GetTokenAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 318
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 319
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table89 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table89.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 320
 await testRunner.AndAsync("I created users for MySQL UserOnlyStore", ((string)(null)), table89, "And ");
#line hidden
                global::Reqnroll.Table table90 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "LoginProvider",
                            "Name",
                            "Value"});
                table90.AddRow(new string[] {
                            "John",
                            "api",
                            "refresh-token",
                            "refresh-value"});
#line 323
 await testRunner.AndAsync("I added user tokens for MySQL UserOnlyStore", ((string)(null)), table90, "And ");
#line hidden
                global::Reqnroll.Table table91 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "LoginProvider",
                            "Name"});
                table91.AddRow(new string[] {
                            "John",
                            "api",
                            "refresh-token"});
#line 326
 await testRunner.WhenAsync("I execute \"GetTokenAsync\" on MySQL UserOnlyStore with parameters", ((string)(null)), table91, "When ");
#line hidden
#line 329
 await testRunner.ThenAsync("the last string result for MySQL UserOnlyStore should be \"refresh-value\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Set authenticator key with SetAuthenticatorKeyAsync without normalized and Guid i" +
            "d")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Set authenticator key with SetAuthenticatorKeyAsync without normalized and Guid i" +
            "d")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task SetAuthenticatorKeyWithSetAuthenticatorKeyAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "51";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Set authenticator key with SetAuthenticatorKeyAsync without normalized and Guid i" +
                    "d", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 332
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 333
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table92 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table92.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 334
 await testRunner.AndAsync("I created users for MySQL UserOnlyStore", ((string)(null)), table92, "And ");
#line hidden
                global::Reqnroll.Table table93 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Key"});
                table93.AddRow(new string[] {
                            "John",
                            "auth-key"});
#line 337
 await testRunner.WhenAsync("I execute \"SetAuthenticatorKeyAsync\" on MySQL UserOnlyStore with parameters", ((string)(null)), table93, "When ");
#line hidden
#line 340
 await testRunner.ThenAsync("the last string result for MySQL UserOnlyStore should be \"auth-key\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Get authenticator key with GetAuthenticatorKeyAsync without normalized and Guid i" +
            "d")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Get authenticator key with GetAuthenticatorKeyAsync without normalized and Guid i" +
            "d")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task GetAuthenticatorKeyWithGetAuthenticatorKeyAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "52";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get authenticator key with GetAuthenticatorKeyAsync without normalized and Guid i" +
                    "d", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 343
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 344
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table94 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table94.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 345
 await testRunner.AndAsync("I created users for MySQL UserOnlyStore", ((string)(null)), table94, "And ");
#line hidden
                global::Reqnroll.Table table95 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Key"});
                table95.AddRow(new string[] {
                            "John",
                            "auth-key"});
#line 348
 await testRunner.AndAsync("I set authenticator keys for MySQL UserOnlyStore", ((string)(null)), table95, "And ");
#line hidden
                global::Reqnroll.Table table96 = new global::Reqnroll.Table(new string[] {
                            "UserName"});
                table96.AddRow(new string[] {
                            "John"});
#line 351
 await testRunner.WhenAsync("I execute \"GetAuthenticatorKeyAsync\" on MySQL UserOnlyStore with parameters", ((string)(null)), table96, "When ");
#line hidden
#line 354
 await testRunner.ThenAsync("the last string result for MySQL UserOnlyStore should be \"auth-key\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Count recovery codes with CountCodesAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Count recovery codes with CountCodesAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task CountRecoveryCodesWithCountCodesAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "53";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Count recovery codes with CountCodesAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 357
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 358
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table97 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table97.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 359
 await testRunner.AndAsync("I created users for MySQL UserOnlyStore", ((string)(null)), table97, "And ");
#line hidden
                global::Reqnroll.Table table98 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "RecoveryCodes"});
                table98.AddRow(new string[] {
                            "John",
                            "code-1;code-2;code-3"});
#line 362
 await testRunner.AndAsync("I replaced recovery codes for MySQL UserOnlyStore", ((string)(null)), table98, "And ");
#line hidden
                global::Reqnroll.Table table99 = new global::Reqnroll.Table(new string[] {
                            "UserName"});
                table99.AddRow(new string[] {
                            "John"});
#line 365
 await testRunner.WhenAsync("I execute \"CountCodesAsync\" on MySQL UserOnlyStore with parameters", ((string)(null)), table99, "When ");
#line hidden
#line 368
 await testRunner.ThenAsync("the last integer result for MySQL UserOnlyStore should be 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Replace recovery codes with ReplaceCodesAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Replace recovery codes with ReplaceCodesAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task ReplaceRecoveryCodesWithReplaceCodesAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "54";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Replace recovery codes with ReplaceCodesAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 371
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 372
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table100 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table100.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 373
 await testRunner.AndAsync("I created users for MySQL UserOnlyStore", ((string)(null)), table100, "And ");
#line hidden
                global::Reqnroll.Table table101 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "RecoveryCodes"});
                table101.AddRow(new string[] {
                            "John",
                            "code-1;code-2;code-3"});
#line 376
 await testRunner.WhenAsync("I execute \"ReplaceCodesAsync\" on MySQL UserOnlyStore with parameters", ((string)(null)), table101, "When ");
#line hidden
#line 379
 await testRunner.ThenAsync("the last integer result for MySQL UserOnlyStore should be 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Redeem recovery code with RedeemCodeAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidUserOnlyStore")]
        [global::Xunit.TraitAttribute("Description", "Redeem recovery code with RedeemCodeAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task RedeemRecoveryCodeWithRedeemCodeAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "55";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Redeem recovery code with RedeemCodeAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 382
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 383
 await testRunner.GivenAsync("I have configured MySQL UserOnlyStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table102 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Email"});
                table102.AddRow(new string[] {
                            "John",
                            "john@example.com"});
#line 384
 await testRunner.AndAsync("I created users for MySQL UserOnlyStore", ((string)(null)), table102, "And ");
#line hidden
                global::Reqnroll.Table table103 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "RecoveryCodes"});
                table103.AddRow(new string[] {
                            "John",
                            "code-1;code-2;code-3"});
#line 387
 await testRunner.AndAsync("I replaced recovery codes for MySQL UserOnlyStore", ((string)(null)), table103, "And ");
#line hidden
                global::Reqnroll.Table table104 = new global::Reqnroll.Table(new string[] {
                            "UserName",
                            "Code"});
                table104.AddRow(new string[] {
                            "John",
                            "code-1"});
#line 390
 await testRunner.WhenAsync("I execute \"RedeemCodeAsync\" on MySQL UserOnlyStore with parameters", ((string)(null)), table104, "When ");
#line hidden
#line 393
 await testRunner.ThenAsync("the last boolean result for MySQL UserOnlyStore should be \"True\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await WithoutNormalizedAspNetIdentityGuidUserOnlyStoreFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await WithoutNormalizedAspNetIdentityGuidUserOnlyStoreFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
