<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <PropertyGroup>
    <ReqnrollUseIntermediateOutputPathForCodeBehind>true</ReqnrollUseIntermediateOutputPathForCodeBehind>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Reqnroll" Version="3.3.4" />
    <PackageReference Include="Reqnroll.Tools.MsBuild.Generation" Version="3.3.4" />
    <PackageReference Include="Reqnroll.xUnit.v3" Version="3.3.4" />
    <PackageReference Remove="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)Common\**\*.cs"
             Link="Common\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="$(MSBuildThisFileDirectory)..\unit\Common\GeneratorCompilation.cs" Link="Common\GeneratorCompilation.cs" />
  </ItemGroup>
</Project>
