// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace AdaskoTheBeAsT.Identity.Dapper.Oracle.IntegrationTest.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class WithoutNormalizedAspNetIdentityGuidRoleStoreFeature : object, global::Xunit.IClassFixture<WithoutNormalizedAspNetIdentityGuidRoleStoreFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "WithoutNormalizedAspNetIdentityGuidRoleStore", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "WithoutNormalizedAspNetIdentityGuidRoleStore.feature"
#line hidden
        
        public WithoutNormalizedAspNetIdentityGuidRoleStoreFeature(WithoutNormalizedAspNetIdentityGuidRoleStoreFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/WithoutNormalizedAspNetIdentityGuidRoleStore.feature.ndjson", 19);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Verify lightweight RoleStore method <method> without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidRoleStore")]
        [global::Xunit.TraitAttribute("Description", "Verify lightweight RoleStore method <method> without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        [global::Xunit.InlineDataAttribute("GetRoleIdAsync", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("GetRoleNameAsync", "1", new string[0])]
        [global::Xunit.InlineDataAttribute("SetRoleNameAsync", "2", new string[0])]
        [global::Xunit.InlineDataAttribute("ConvertIdFromString", "3", new string[0])]
        [global::Xunit.InlineDataAttribute("ConvertIdToString", "4", new string[0])]
        [global::Xunit.InlineDataAttribute("GetNormalizedRoleNameAsync", "5", new string[0])]
        [global::Xunit.InlineDataAttribute("SetNormalizedRoleNameAsync", "6", new string[0])]
        [global::Xunit.InlineDataAttribute("Dispose", "7", new string[0])]
        public async global::System.Threading.Tasks.Task VerifyLightweightRoleStoreMethodMethodWithoutNormalizedAndGuidId(string method, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("method", method);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify lightweight RoleStore method <method> without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.GivenAsync("I have configured Oracle RoleStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
 await testRunner.WhenAsync(string.Format("I verify \"{0}\" on Oracle RoleStore without normalized and Guid id", method), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
 await testRunner.ThenAsync(string.Format("\"{0}\" on Oracle RoleStore should work without normalized and Guid id", method), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Query Roles without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidRoleStore")]
        [global::Xunit.TraitAttribute("Description", "Query Roles without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task QueryRolesWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Query Roles without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 23
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 24
 await testRunner.GivenAsync("I have configured Oracle RoleStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Name"});
                table1.AddRow(new string[] {
                            "Administrator"});
                table1.AddRow(new string[] {
                            "Auditor"});
#line 25
 await testRunner.AndAsync("I created roles for Oracle RoleStore", ((string)(null)), table1, "And ");
#line hidden
#line 29
 await testRunner.WhenAsync("I execute \"Roles\" on Oracle RoleStore", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Name"});
                table2.AddRow(new string[] {
                            "Administrator"});
                table2.AddRow(new string[] {
                            "Auditor"});
#line 30
 await testRunner.ThenAsync("the last roles result for Oracle RoleStore should match", ((string)(null)), table2, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Create role with CreateAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidRoleStore")]
        [global::Xunit.TraitAttribute("Description", "Create role with CreateAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task CreateRoleWithCreateAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create role with CreateAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 37
 await testRunner.GivenAsync("I have configured Oracle RoleStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "ConcurrencyStamp"});
                table3.AddRow(new string[] {
                            "Administrator",
                            "role-create"});
#line 38
 await testRunner.WhenAsync("I execute \"CreateAsync\" on Oracle RoleStore with parameters", ((string)(null)), table3, "When ");
#line hidden
#line 41
 await testRunner.ThenAsync("the last identity result for Oracle RoleStore should be successful", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Name"});
                table4.AddRow(new string[] {
                            "Administrator"});
#line 42
 await testRunner.AndAsync("the last role result for Oracle RoleStore should match", ((string)(null)), table4, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Update role with UpdateAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidRoleStore")]
        [global::Xunit.TraitAttribute("Description", "Update role with UpdateAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task UpdateRoleWithUpdateAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Update role with UpdateAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 47
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 48
 await testRunner.GivenAsync("I have configured Oracle RoleStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Name"});
                table5.AddRow(new string[] {
                            "Administrator"});
#line 49
 await testRunner.AndAsync("I created roles for Oracle RoleStore", ((string)(null)), table5, "And ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "RoleName",
                            "NewName",
                            "NewConcurrencyStamp"});
                table6.AddRow(new string[] {
                            "Administrator",
                            "Administrators",
                            "role-updated"});
#line 52
 await testRunner.WhenAsync("I execute \"UpdateAsync\" on Oracle RoleStore with parameters", ((string)(null)), table6, "When ");
#line hidden
#line 55
 await testRunner.ThenAsync("the last identity result for Oracle RoleStore should be successful", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Name"});
                table7.AddRow(new string[] {
                            "Administrators"});
#line 56
 await testRunner.AndAsync("the last role result for Oracle RoleStore should match", ((string)(null)), table7, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Delete role with DeleteAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidRoleStore")]
        [global::Xunit.TraitAttribute("Description", "Delete role with DeleteAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task DeleteRoleWithDeleteAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Delete role with DeleteAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 61
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 62
 await testRunner.GivenAsync("I have configured Oracle RoleStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "Name"});
                table8.AddRow(new string[] {
                            "Administrator"});
#line 63
 await testRunner.AndAsync("I created roles for Oracle RoleStore", ((string)(null)), table8, "And ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "RoleName"});
                table9.AddRow(new string[] {
                            "Administrator"});
#line 66
 await testRunner.WhenAsync("I execute \"DeleteAsync\" on Oracle RoleStore with parameters", ((string)(null)), table9, "When ");
#line hidden
#line 69
 await testRunner.ThenAsync("the last identity result for Oracle RoleStore should be successful", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 70
 await testRunner.AndAsync("the last role result for Oracle RoleStore should be null", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Find role with FindByIdAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidRoleStore")]
        [global::Xunit.TraitAttribute("Description", "Find role with FindByIdAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task FindRoleWithFindByIdAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Find role with FindByIdAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 73
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 74
 await testRunner.GivenAsync("I have configured Oracle RoleStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "Name"});
                table10.AddRow(new string[] {
                            "Administrator"});
#line 75
 await testRunner.AndAsync("I created roles for Oracle RoleStore", ((string)(null)), table10, "And ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "RoleName"});
                table11.AddRow(new string[] {
                            "Administrator"});
#line 78
 await testRunner.WhenAsync("I execute \"FindByIdAsync\" on Oracle RoleStore with parameters", ((string)(null)), table11, "When ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "Name"});
                table12.AddRow(new string[] {
                            "Administrator"});
#line 81
 await testRunner.ThenAsync("the last role result for Oracle RoleStore should match", ((string)(null)), table12, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Find role with FindByNameAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidRoleStore")]
        [global::Xunit.TraitAttribute("Description", "Find role with FindByNameAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task FindRoleWithFindByNameAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Find role with FindByNameAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 86
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 87
 await testRunner.GivenAsync("I have configured Oracle RoleStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "Name"});
                table13.AddRow(new string[] {
                            "Administrator"});
#line 88
 await testRunner.AndAsync("I created roles for Oracle RoleStore", ((string)(null)), table13, "And ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "RoleName"});
                table14.AddRow(new string[] {
                            "Administrator"});
#line 91
 await testRunner.WhenAsync("I execute \"FindByNameAsync\" on Oracle RoleStore with parameters", ((string)(null)), table14, "When ");
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "Name"});
                table15.AddRow(new string[] {
                            "Administrator"});
#line 94
 await testRunner.ThenAsync("the last role result for Oracle RoleStore should match", ((string)(null)), table15, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Get role claims with GetClaimsAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidRoleStore")]
        [global::Xunit.TraitAttribute("Description", "Get role claims with GetClaimsAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task GetRoleClaimsWithGetClaimsAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Get role claims with GetClaimsAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 99
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 100
 await testRunner.GivenAsync("I have configured Oracle RoleStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "Name"});
                table16.AddRow(new string[] {
                            "Administrator"});
#line 101
 await testRunner.AndAsync("I created roles for Oracle RoleStore", ((string)(null)), table16, "And ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "RoleName",
                            "ClaimType",
                            "ClaimValue"});
                table17.AddRow(new string[] {
                            "Administrator",
                            "permission",
                            "manage-users"});
                table17.AddRow(new string[] {
                            "Administrator",
                            "permission",
                            "audit-users"});
#line 104
 await testRunner.AndAsync("I added role claims for Oracle RoleStore", ((string)(null)), table17, "And ");
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "RoleName"});
                table18.AddRow(new string[] {
                            "Administrator"});
#line 108
 await testRunner.WhenAsync("I execute \"GetClaimsAsync\" on Oracle RoleStore with parameters", ((string)(null)), table18, "When ");
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "ClaimType",
                            "ClaimValue"});
                table19.AddRow(new string[] {
                            "permission",
                            "manage-users"});
                table19.AddRow(new string[] {
                            "permission",
                            "audit-users"});
#line 111
 await testRunner.ThenAsync("the last claims result for Oracle RoleStore should match", ((string)(null)), table19, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Add role claim with AddClaimAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidRoleStore")]
        [global::Xunit.TraitAttribute("Description", "Add role claim with AddClaimAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task AddRoleClaimWithAddClaimAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Add role claim with AddClaimAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 117
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 118
 await testRunner.GivenAsync("I have configured Oracle RoleStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table20 = new global::Reqnroll.Table(new string[] {
                            "Name"});
                table20.AddRow(new string[] {
                            "Administrator"});
#line 119
 await testRunner.AndAsync("I created roles for Oracle RoleStore", ((string)(null)), table20, "And ");
#line hidden
                global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                            "RoleName",
                            "ClaimType",
                            "ClaimValue"});
                table21.AddRow(new string[] {
                            "Administrator",
                            "permission",
                            "manage-users"});
#line 122
 await testRunner.WhenAsync("I execute \"AddClaimAsync\" on Oracle RoleStore with parameters", ((string)(null)), table21, "When ");
#line hidden
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            "ClaimType",
                            "ClaimValue"});
                table22.AddRow(new string[] {
                            "permission",
                            "manage-users"});
#line 125
 await testRunner.ThenAsync("the last claims result for Oracle RoleStore should match", ((string)(null)), table22, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Remove role claim with RemoveClaimAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("FeatureTitle", "WithoutNormalizedAspNetIdentityGuidRoleStore")]
        [global::Xunit.TraitAttribute("Description", "Remove role claim with RemoveClaimAsync without normalized and Guid id")]
        [global::Xunit.TraitAttribute("Category", "xunit:collection[DatabaseWithGuidIdCollection]")]
        public async global::System.Threading.Tasks.Task RemoveRoleClaimWithRemoveClaimAsyncWithoutNormalizedAndGuidId()
        {
            string[] tagsOfScenario = new string[] {
                    "xunit:collection[DatabaseWithGuidIdCollection]"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Remove role claim with RemoveClaimAsync without normalized and Guid id", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 130
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 131
 await testRunner.GivenAsync("I have configured Oracle RoleStore without normalized and Guid id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "Name"});
                table23.AddRow(new string[] {
                            "Administrator"});
#line 132
 await testRunner.AndAsync("I created roles for Oracle RoleStore", ((string)(null)), table23, "And ");
#line hidden
                global::Reqnroll.Table table24 = new global::Reqnroll.Table(new string[] {
                            "RoleName",
                            "ClaimType",
                            "ClaimValue"});
                table24.AddRow(new string[] {
                            "Administrator",
                            "permission",
                            "manage-users"});
                table24.AddRow(new string[] {
                            "Administrator",
                            "permission",
                            "audit-users"});
#line 135
 await testRunner.AndAsync("I added role claims for Oracle RoleStore", ((string)(null)), table24, "And ");
#line hidden
                global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                            "RoleName",
                            "ClaimType",
                            "ClaimValue"});
                table25.AddRow(new string[] {
                            "Administrator",
                            "permission",
                            "manage-users"});
#line 139
 await testRunner.WhenAsync("I execute \"RemoveClaimAsync\" on Oracle RoleStore with parameters", ((string)(null)), table25, "When ");
#line hidden
                global::Reqnroll.Table table26 = new global::Reqnroll.Table(new string[] {
                            "ClaimType",
                            "ClaimValue"});
                table26.AddRow(new string[] {
                            "permission",
                            "audit-users"});
#line 142
 await testRunner.ThenAsync("the last claims result for Oracle RoleStore should match", ((string)(null)), table26, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await WithoutNormalizedAspNetIdentityGuidRoleStoreFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await WithoutNormalizedAspNetIdentityGuidRoleStoreFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
